version: '3'

services:
  mydocker:
    container_name: mydocker-test
    image: nginx:alpine
    restart: always
    volumes:
      - ./:/usr/share/nginx/html
    env_file:
      - .env
    expose:
      - 80

networks:
  default:
    external:
      name: nginx-proxy
